### ISSUE TITLE
CD Colors fixed in Wordpress

### ISSUE THREAD

**Issue by MartinaSpringmann** [errnesto/ffa-website#48]
Einfach alle Farben aus dem CD in Worpress einfügen, damit diese nicht per #406324 eintegragen werden müssen, sondern nur ausgewählt werden können

**Comment by errnesto** [comment]
In some cases we have a category selector to selct colors I think this is a better option.
So the style and the content is somewhat seperated.

A real inline color picker is out of scope anyway
